# -*- coding: utf-8 -*-
"""Trader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uWgk-Ur4xe915s06GB4NtuJfLAOrDtR0
"""

import random
class Trader:
    def __init__(self,money,custom):
        #constructor
        self.money=money
        self.custom=custom
    

myTrader=Trader(random.randrange(800),random.randrange(800))
counter=0
while (myTrader.money>0 and myTrader.custom>0):
  counter+=1
  print("Now you have {} dolar and our remaining stock is {} .This is your {}th expense".format(myTrader.money,myTrader.custom,counter))
  myTrader.money-=1
  myTrader.custom-=1

